package day14_exception_demo;

import java.util.Scanner;

public class Unchecked_exception_Handle_exceptions {

	public static void main(String[] args) {
		//TODO Auto-generated method stub
		/*Scanner sc=new Scanner(System.in);
		System.out.println("enter a number");
		int num=sc.nextInt();
		try 
		{
		System.out.println("enter the name of employ");
		}
		catch(ArithmeticException e)
		{
			System.out.println("you have provided inavalid input,please provide corect input");
		}*/

		/*Scanner sc=new Scanner(System.in);
		System.out.println("enter a number");
		int num=sc.nextInt();
		try 
		{
		System.out.println(100/num);
		}
		catch(ArithmeticException e)
		{
			System.out.println("you have provided inavalid input,please provide corect input");
		}
		catch(NumberFormatException a)
		{
			System.out.println("you have provided inavalid input,please provide corect input");
		}
		catch(ArrayIndexOutOfBoundsException t)*/
		{
		/*	System.out.println("you have provided inavalid input,please provide corect input");
			enter a number
			0
			you have provided inavalid input,please provide corect input*/
			
			
		/*	Scanner sc=new Scanner(System.in);
			System.out.println("enter a number");
			int num=sc.nextInt();
			try 
			{
			System.out.println(100/num);
			}
			catch(Exception e)
			{
				System.out.println("exception occured and handled");
				enter a number
				0
				exception occured and handled*/
			

			
			}

		}
	}

